### ISSUE TITLE
packages not found

### ISSUE THREAD

**Issue by adundarov** [PhDN/NoCheat#9]
#### Issue description
--could not run python.main

#### Steps to reproduce the issue
--follow setup instructions on wsl, and execute main.py

#### What's the expected result?
--start the nocheat server

#### What's the actual result?
--error:

     I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network 
     Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
     To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
      * Serving Flask app 'main'
      * Debug mode: off
     Permission denied

#### Additional details / screenshot

--PC Spec
     [specs.txt](https://github.com/PhDN/NoCheat/files/10856790/specs.txt)

**Comment by adundarov** [comment]
possible fix is replacing python-magic in dependencies with:
  - pip
  - pip: 
    - python-magic

**Comment by adundarov** [comment]
nvm, did not work, gave this error later when running main.py:

Traceback (most recent call last):
  File "C:\Users\Alex\Desktop\cse403\NoCheat\src\back\main.py", line 11, in <module>
    from Controller import parse_file, Controller
  File "C:\Users\Alex\Desktop\cse403\NoCheat\src\back\Controller.py", line 4, in <module>
    import magic
  File "C:\Users\Alex\anaconda3\envs\nocheat\lib\site-packages\magic\__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
  File "C:\Users\Alex\anaconda3\envs\nocheat\lib\site-packages\magic\loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
